version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/ihavespoons/zrok/cmd.version={{.Version}}
      - -X github.com/ihavespoons/zrok/cmd.commit={{.Commit}}
      - -X github.com/ihavespoons/zrok/cmd.date={{.Date}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - skills/**/*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

release:
  prerelease: auto
  footer: |
    ## Installation

    **Homebrew (macOS/Linux):**
    ```bash
    brew install ihavespoons/tap/zrok
    ```

    **Go install:**
    ```bash
    go install github.com/ihavespoons/zrok@latest
    ```

brews:
  - name: zrok
    repository:
      owner: ihavespoons
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/ihavespoons/zrok"
    description: "LLM-assisted code review tool with agent orchestration"
    license: "Apache-2.0"
    test: |
      system "#{bin}/zrok", "--version"
